# Generated by Django 4.0.5 on 2022-10-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Standard', models.IntegerField()),
                ('Subject', models.CharField(max_length=50)),
                ('Marks', models.IntegerField()),
                ('sports', models.CharField(max_length=50)),
            ],
        ),
    ]
